### ISSUE TITLE
Where to set caching?

### ISSUE THREAD

**Issue by scharf** [locize/locize-docs#3]
I cannot figure out where to change the caching. In the docu it says how but not where it is in the UI: https://github.com/locize/locize-docs/blob/master/caching.md

From the screenshot I guess, it is somewhere in the settings, but I cannot find it:

![locize_io____setting](https://user-images.githubusercontent.com/3731059/34942476-1acdae88-f9f8-11e7-98f0-38d2d5ee050f.jpg)

**Comment by jamuhl** [comment]
Hi Michael,

Caching is set per version and therefor placed under the more options of the versions card:



If there is anything else we could help with let me know.

Best, Jan

locize.com
